<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jsd_sprechstunden"
 *
 * Auto generated by Extension Builder 2021-02-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JDI Sprechstunden',
    'description' => 'Sprechstunden der Krankenhäuser',
    'category' => 'plugin',
    'author' => 'Robert Heyduck',
    'author_email' => 'mail@typo-script.de',
    'state' => 'stable',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
